version: '3.8'

services:
  hub:
    image: selenium/hub:3
    ports:
      - 9444:4444
    expose:
      - 4444
    networks:
      - selenium-grid

  chrome:
    shm_size: 2gb
    image: selenium/node-chrome-debug:3
    #image: selenium/node-chrome:84.0.4147.105
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_HOST=hub
      - VNC_NO_PASSWORD=1
    volumes:
      - ../resources:/usr/share/jitsi-meet-torture/resources
    # ports:
      # - 5900:5900
    depends_on:
      - hub
    networks:
      - selenium-grid
    deploy:
        replicas: 10

 # mvn:
 #   build: ./mvn
 #   depends_on:
 #     - hub
 #   networks:
 #     - selenium-grid

networks:
  selenium-grid:
